version: "3"

services: 
  valheim: 
    image: "ghcr.io/lloesche/valheim-server"
    cap_add:
      - "sys_nice"
    volumes: 
      - "./config:/config"
      - "./data:/opt/valheim"
    ports: 
      - "2456-2457:2456-2457/udp"
    env_file:
      - "./.env"
    restart: always
    stop_grace_period: 2m
